# App Name
spring.application.name=capturelife

# ===============================
# DATABASE (Supabase - FIXED)
# ===============================

# Use Supabase Pooler (IMPORTANT)
spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require

spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# REMOVE THIS (warning aa raha tha)
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# EMAIL CONFIG (GMAIL SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# SERVER
# ===============================
server.port=8080