spring.application.name=capturelife

spring.datasource.url=jdbc:postgresql://db.etupdfbaxummolwfatjx.supabase.co:6543/postgres?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Xarq3mBxpgVmU8C7

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pksaw7717@gmail.com
spring.mail.password=xadthdkerfcrzakp

server.port=${PORT:8080}