spring.application.name=capturelife

spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres.etupdfbaxummolwfatjx
spring.datasource.password=Xarq3mBxpgVmU8C7

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pksaw7717@gmail.com
spring.mail.password=xadthdkerfcrzakp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=${PORT:8080}